version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    depends_on:
      - db
  
  db:
    image: "postgres"
    environment:
      - POSTGRES_HOST=
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
