version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=lead_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
  
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lead_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
